### ISSUE TITLE
ERROR 500

### ISSUE THREAD

**Issue by SubmeetVet** [sensiolabs/BehatPageObjectExtension#130]
How to fix?

Error details: Type: Exception Message: Call to a member function open() on null File: /home/submysno/public_html/ow_plugins/ivideo/controllers/action.php Line: 151 Trace: #0 [internal function]: IVIDEO_CTRL_Action->upload(Array) #1 /home/submysno/public_html/ow_core/request_handler.php(250): ReflectionMethod->invokeArgs(Object(IVIDEO_CTRL_Action), Array) #2 /home/submysno/public_html/ow_core/request_handler.php(226): OW_RequestHandler->processControllerAction(Object(ReflectionMethod), Object(IVIDEO_CTRL_Action)) #3 /home/submysno/public_html/ow_core/application.php(346): OW_RequestHandler->dispatch() #4 /home/submysno/public_html/index.php(76): OW_Application->handleRequest() #5 {main}

**Comment by jakzal** [comment]
It looks like there's a problem with your application.

**Comment by SubmeetVet** [comment]
Hi Jakzal,

What I know, the Video Upload plugin does not work, and gives such an error after uploading the video, host program cPanel, PHP7.2, MariaDB 10.3

**Comment by DonCallisto** [comment]
@SubmeetVet This issue is not related anyhow with this extension (stacktrace provided gives the evidence of what I'm claiming).
