### ISSUE TITLE
Outdated Documentation

### ISSUE THREAD

**Issue by benztest** [sensiolabs/BehatPageObjectExtension#133]
When following the documentation at [readthedocs](https://behat-page-object-extension.readthedocs.io/en/stable/) several links throughout are out of date and link to dead pages. 

Please could a full example of code be included as well. (Especially around nested elements)
As the error message `"getElement" method is not available on the MyExample (BadMethodCallException)` is really not clear.

Thanks,
Ben

**Comment by jakzal** [comment]
Could you paste a code snippet to show what you're trying to do?

**Comment by benztest** [comment]
Hi @jakzal,

Thanks for the response, I no longer require assistance with nested elements. I've since restarted a number of times and the issues I was likely encountering is either related to my composer setup or I did not replace `$this->getDriver()` with `$this->getSession()`. 

----
The docs however are outdated and the example about nested elements also contains an error:
`    public function logo()
    {
        return $this->getElement('Logo')'
    }
`
>
`    public function logo()
    {
        return $this->getElement('Logo');
    }`
