### ISSUE TITLE
Trying to get in touch regarding a security issue

### ISSUE THREAD

**Issue by JamieSlome** [sensiolabs/BehatPageObjectExtension#139]
Hey there!

I'd like to report a security issue but cannot find contact instructions on your repository.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by jakzal** [comment]
Feel free to contact me at jakub AT zalas DOT pl. I'm interested to see what security problems might a testing tool have.

**Comment by jakzal** [comment]
For full visibility, this is where the "vulnerability" was discovered :)

https://github.com/sensiolabs/BehatPageObjectExtension/blob/6e86a17c7a9ea90ccd8d5ff98beeec24abeb7f7c/features/application/index.php#L16-L17

Nothing to worry about.

**Comment by DonCallisto** [comment]
Thanks for the update. I was worried and about to ask you more infos.
Cheers.
