### ISSUE TITLE
Option to ignore protocol in verifyUrl

### ISSUE THREAD

**Issue by slde-gorillaman** [sensiolabs/BehatPageObjectExtension#59]
I encountered a problem for a particular case where only one page uses HTTPS but the verifyUrl kept throwing an Exception as the expected and actual URL are different upon redirection on HTTPS.

Currently I overriden the verifyUrl to ignore the protocol used, however it would be great to have this configurable through the pageParameters (maybe it is already present? Am I missing something?).

Idea would be to specify the allowed protocols in the parameters.

**Comment by jakzal** [comment]
I would either make the verifyUrl less strict (don't compare the protocol at all), or provide an empty implementation so the end user could provide their own.

**Comment by slde-gorillaman** [comment]
For my concrete implementation I have simply overridden the verifyUrl method. Could be that this is enough, not sure how often that case is encountered. 

I'd leave the original implementation as is.

**Comment by jakzal** [comment]
All the verify* methods exist in order to be overridden and adapted to custom cases.
