### ISSUE TITLE
Element can't return other elements

### ISSUE THREAD

**Issue by DonCallisto** [sensiolabs/BehatPageObjectExtension#79]
Why can't [Element](https://github.com/sensiolabs/BehatPageObjectExtension/blob/master/src/SensioLabs/Behat/PageObjectExtension/PageObject/Element.php) returns an `Element` itself?

Is it "by design"? There are motivations that, at the moment, I can't understand?

If it is an interesting behavior let me know and I'll make a PR.

**Comment by jakzal** [comment]
> Why can't Element returns an Element itself?

Do you mean a method on element returning an element?

**Comment by DonCallisto** [comment]
> Do you mean a method on element returning an element? Not sure what you're asking :)

Yes :)

**Comment by DonCallisto** [comment]
So, is that an unwanted feature or it is a missing one?

**Comment by jakzal** [comment]
I guess no one ever needed it before. If you have a use case, send a PR please! :)

**Comment by DonCallisto** [comment]
I have a real example: form with tabs where every tab have some elements and tab itself (that's not a page, but an element of form itself) is used in other forms.

If that is legitimate, I'll make the PR. Let me know :)

**Comment by jakzal** [comment]
Let me say it this way: if you have a valid use case and really need this method, submit a PR please :) looks like no one has needed it so far, that's why it's not there.

**Comment by DonCallisto** [comment]
Ok, let's freeze this and wait to see if someone else have a *valid* use case or if I found new ones that needs this change.

**Comment by stephenharris** [comment]
I have another use case: a `table` element - which contains a number of row elements. 

This actually relates to another feature request I have, and for which I'll try to open a PR shortly - and that's the ability to extend `InlineElement`. These table row elements would need to be `InlineElement`s as they have identical behaviour, but with different selectors (which are not known a priori), but I would like to be able to furnish them with additional methods.
