### ISSUE TITLE
Custom Element throwing exception

### ISSUE THREAD

**Issue by mi-haque** [sensiolabs/BehatPageObjectExtension#91]
I have tried to access a custom element class 'Wait' using $this->getElement('Wait')->waitForPageLoad();. It's throwing the following exception:
invalid selector: Unable to locate an element with the xpath expression //html// because of the following error:
      SyntaxError: Failed to execute 'evaluate' on 'Document': The string '//html//' is not a valid XPath expression.
        (Session info: chrome=58.0.3029.110)
        (Driver info: chromedriver=2.29.461585 (0be2cd95f834e9ee7c46bcc7cf405b483f5ae83b),platform=Mac OS X 10.12.5 x86_64) (WARNING: The server did not provide any stacktrace information)
      Command duration or timeout: 25 milliseconds
      For documentation on this error, please visit: http://seleniumhq.org/exceptions/invalid_selector_exception.html
      Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
      System info: host: 'GMX203734MC.local', ip: 'fe80:0:0:0:cf1:95e8:899e:17a3%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.5', java.version: '1.8.0_131'
      Driver info: org.openqa.selenium.chrome.ChromeDriver
      Capabilities [{applicationCacheEnabled=false, rotatable=false, mobileEmulationEnabled=false, networkConnectionEnabled=false, chrome={chromedriverVersion=2.29.461585 (0be2cd95f834e9ee7c46bcc7cf405b483f5ae83b), userDataDir=/var/folders/55/5mcn6tyj6tq5bz8l4scqb21hmmpjkm/T/.org.chromium.Chromium.34qI5A}, takesHeapSnapshot=true, pageLoadStrategy=normal, databaseEnabled=false, handlesAlerts=true, hasTouchScreen=false, version=58.0.3029.110, platform=MAC, browserConnectionEnabled=false, nativeEvents=true, acceptSslCerts=true, locationContextEnabled=true, webStorageEnabled=true, browserName=chrome, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true, unexpectedAlertBehaviour=}]
      Session ID: 8500abba0171fe3998cb3541ea695aa2

**Comment by jakzal** [comment]
How's your element defined?

**Comment by mi-haque** [comment]
I have defined the element under bootstrap/Page/Element. I had mentioned the name space in yml file also (element: [Page\Element]). Here Wait is a class defined under Element folder. When i tried with some non existing random class name, it threw an error of non exist element. When I trying to access the element which is defined, then it throwing the weird exception

**Comment by DonCallisto** [comment]
@mi-haque have you defined the `$selector` property as stated [here](http://behat-page-object-extension.readthedocs.io/en/stable/guide/working_with_elements.html#custom-elements)?

**Comment by mi-haque** [comment]
oh..no..Ok I understand it now. I thought we can use Element as a place of common methods. Thanks dude...
