### ISSUE TITLE
Ability to reuse code among page/element objects

### ISSUE THREAD

**Issue by walterdolce** [sensiolabs/BehatPageObjectExtension#96]
Unless I'm missing something, doesn't seem the extension allows for DI into page/element objects.

Example:

```
# LoginPage
class LoginPage extends Page
# ...
    public function loginWith($username, $password)
    {
        $this->getElement(Username::class)->setValue($username);
        $this->getElement(Password::class)->setValue($password);
        $this->getElement(LoginButton::class)->click();
    }


# CheckoutStepOnePage
class RegisterPage extends Page
# ...
    public function loginWith($username, $password)
    {
        $this->getElement(Username::class)->setValue($username);
        $this->getElement(Password::class)->setValue($password);
        $this->getElement(LoginButton::class)->click();
    }
```

If I wanted to extract the three `getElement` calls, the only way to share this code would be via traits it seems. That is something I am trying hard to avoid.

What I am also trying hard to avoid, is to get into the inner workings of the extension. That is, to use the factories, etc myself and change them to suit my needs (too much boilerplate).

What would be the best way for page/element objects reuse code (i.e. helpers, etc)?

Thank you.

**Comment by jakzal** [comment]
Hm, perhaps I'm missing something, but couldn't you just create a new element for this use case? 

```php
class LoginBox extends Element
{
    public function loginWith($username, $password)
    {
        $this->getElement(Username::class)->setValue($username);
        $this->getElement(Password::class)->setValue($password);
        $this->getElement(LoginButton::class)->click();
    }
}
```


```php
# LoginPage
class LoginPage extends Page
{
    public function loginWith($username, $password)
    {
        $this->getElement(LoginBox::class)->loginWith($username, $password);
    }
}


# CheckoutStepOnePage
class RegisterPage extends Page
{
    public function loginWith($username, $password)
    {
           $this->getElement(LoginBox::class)->loginWith($username, $password);
    }
}
```

**Comment by walterdolce** [comment]
Hmmmmmmmmm. Yep, that would actually do it. What's more funny, I have been doing this in the past, too.

Thank you for showing me the forest through the trees, oh master.

![](https://metrouk2.files.wordpress.com/2015/12/yoda1.gif)
