### ISSUE TITLE
Remove path and selector from page and element

### ISSUE THREAD

**Issue by DonCallisto** [sensiolabs/BehatPageObjectExtension#97]
Hi @jakzal, why are we using a protected property?
Shouldn't be better to declare [this](https://github.com/sensiolabs/BehatPageObjectExtension/blob/master/src/PageObject/Page.php#L161-L168) an abstract method (as well as `selector` for elements)?

If this could be an improvement, we can include this for a next major release and introduce a deprecation message to the current one.

What do you think?

**Comment by jakzal** [comment]
As I said in https://github.com/sensiolabs/BehatPageObjectExtension/pull/99#issuecomment-334140611 I don't even remember why this is protected. Perhaps I thought people will find it useful to override it, but I didn't want to force them to implement the method as it's actually not required, unless you call `open()` on a page (not every page is opened directly, in most cases they're returned as a result of method calls on other pages).

Anyway, In the referenced ticket I gave some ideas on how we could improve the current state. I'd appreciate your input.

**Comment by DonCallisto** [comment]
Ok, let's continue in #99
